# Generated by Django 5.1.4 on 2025-01-10 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('student_class', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('father_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('parent_mobile', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(max_length=10)),
                ('race_religion', models.CharField(max_length=50)),
                ('aadhar', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('caste', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=255)),
                ('school_district', models.CharField(max_length=100)),
                ('school_city', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
                ('total_marks', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('place', models.CharField(max_length=100)),
                ('form_date', models.DateField()),
                ('photograph', models.FileField(blank=True, null=True, upload_to='uploads/photograph/')),
                ('application_form', models.FileField(blank=True, null=True, upload_to='uploads/application_form/')),
                ('higher_secondary_certificate', models.FileField(blank=True, null=True, upload_to='uploads/higher_secondary_certificate/')),
                ('caste_certificate', models.FileField(blank=True, null=True, upload_to='uploads/caste_certificate/')),
                ('ssc_hsc_marksheets', models.FileField(blank=True, null=True, upload_to='uploads/ssc_hsc_marksheets/')),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='uploads/aadhar_card')),
                ('marriage_certificate', models.FileField(blank=True, null=True, upload_to='uploads/marriage_certificate')),
                ('other_qualifications', models.FileField(blank=True, null=True, upload_to='uploads/other_qualifications')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Signup_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrollment_no', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('blood_group', models.CharField(max_length=3)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=15)),
                ('about_yourself', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='database.class')),
            ],
        ),
        migrations.CreateModel(
            name='ExamMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.student_profile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.subject')),
            ],
        ),
    ]
