# Generated by Django 5.1.4 on 2025-01-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exammarks',
            old_name='student_profile',
            new_name='student',
        ),
        migrations.AddField(
            model_name='exammarks',
            name='class_name',
            field=models.CharField(default='BCA', max_length=10),
        ),
        migrations.AddField(
            model_name='exammarks',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exammarks',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
