# Generated by Django 5.1.4 on 2025-01-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_student_profile_exammarks_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='form_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='signup_user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='signup_user',
            name='username',
            field=models.CharField(max_length=122, unique=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='enrollment_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
