# Generated by Django 5.1.4 on 2025-01-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_admissionform_aadhar_alter_admissionform_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='aadhar',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
