# Generated by Django 5.1.4 on 2025-01-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='aadhar',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='form_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='signup_user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='signup_user',
            name='username',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='enrollment_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
